name: use Docker image
on: workflow_dispatch

jobs:
  clone-and-build:
    runs-on: ubuntu-latest
    container: ghcr.io/bolinfest/ghstack-testing/demo:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: pwd
        run: pwd
      - name: git log
        run: git log
      - name: Run something
        run: echo $(uname -r)
      - name: Run node version
        run: node --version
