name: use Docker image
on: workflow_dispatch

jobs:
  clone-and-build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/bolinfest/ghstack-testing/demo:latest
      # options: --user root
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: grant access
        run: git config --global --add safe.directory "$PWD"
      - name: git log
        run: git log
      - name: Run something
        run: echo $(uname -r)
      - name: Run node version
        run: node --version
